config/routes.rb
NetworkDossier::Application.routes.draw do
  get "top/home"
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'top#home'

  resources :events, only: [:index, :show] do
    member do
      put :update_notes
    end
  end

end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  belongs_to :event
  belongs_to :meetup_profile
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :attendances
  has_many :meetup_profiles, through: :attendances
end

app/models/meetup_profile.rb
class MeetupProfile < ActiveRecord::Base
  has_many :attendances
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :owner, class_name: :user
  belongs_to :about, class_name: 'MeetupProfile'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :registerable, :recoverable, :validatable
  devise :omniauthable, :rememberable, :trackable, :database_authenticatable, :omniauth_providers => [:meetup]
  belongs_to :meetup_profile

  has_many :attendances, through: :meetup_profile
  has_many :events, through: :attendances
  has_many :notes, foreign_key: :owner_id
  has_many :noted, through: :notes, class_name: 'MeetupProfile', source: :about

  accepts_nested_attributes_for :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :update_notes]

  # GET /events
  # GET /events.json
  def index
    @events = current_user.events.order('time DESC').all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  def update_notes
    params[:notes_attributes].keys.each do |attendee_id|
      note = (current_user.notes.where(about_id: attendee_id).first() or current_user.notes.new(about_id: attendee_id))
      note.note_text = params[:notes_attributes][attendee_id][:note_text]
      note.save!
      note.delete unless note.note_text
    end
    redirect_to @event, notice: 'Notes updated'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = current_user.events.find(params[:id])
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
require 'rmeetup_override'

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def meetup
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    omniauth_data = request.env["omniauth.auth"]
    meetup_profile = MeetupProfile.find_by_id(omniauth_data["uid"])
    if not meetup_profile then
      meetup_profile = MeetupProfile.new
      meetup_profile.id = omniauth_data["uid"]
    end

    # Fill in data
    meetup_profile.name = omniauth_data["info"]["name"]
    meetup_profile.photo_url = omniauth_data["info"]["photo_url"]
    meetup_profile.access_token = omniauth_data["credentials"]["token"]
    meetup_profile.refresh_token = omniauth_data["credentials"]["refresh_token"]
    meetup_profile.access_expiration = omniauth_data["credentials"]["expires_at"]
    meetup_profile.other_services = omniauth_data["extra"]["raw_info"]["other_services"].to_s
    meetup_profile.save!

    @user = User.find_by_meetup_profile_id(meetup_profile.id)
    unless @user then
      @user = User.new
      @user.meetup_profile = meetup_profile
      @user.save!
    end

    results = RMeetup::Client.fetch(:events, {member_id: meetup_profile.id, access_token: meetup_profile.access_token, status: 'past,upcoming', rsvp: 'yes'})
    results.each do |result|
      event = Event.find_by_meetup_id(result.event['id'])
      if not event then
        event = Event.new
        event.meetup_id = result.event['id']
      end
      event.name = result.event['name']
      event.group_name = result.event['group']['name']
      event.venue_name = result.event['venue']['name']
      event.time = Time.at(result.event['time'].to_i / 1000)
      event.meetup_url = result.event['event_url']
      event.save!

      rsvps = RMeetup::Client.fetch(:rsvps, {event_id: event.meetup_id, access_token: meetup_profile.access_token, rsvp: 'yes'})
      rsvps.each do |rsvp|
        profile = MeetupProfile.find_by_id(rsvp.member['member_id'])
        profile = MeetupProfile.new(id: rsvp.member['member_id']) unless profile

        profile.name = rsvp.member['name']
        profile.photo_url = rsvp.member_photo['photo_link'] if rsvp.member_photo
        profile.save()

        event.attendances.find_or_create_by(meetup_profile_id: profile.id)
      end
    end

    sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
    set_flash_message(:notice, :success, :kind => "Meetup") if is_navigational_format?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def setup_user(user, event)
    (event.meetup_profiles.all - user.noted).each do |profile|
      user.notes.build(about: profile)
    end
    return user
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/events/index.html.haml
%h1 Listing events

%table
  - @events.each do |event|
    %tr
      %td= event.time
      %td= event.name
      %td= event.group_name
      %td= event.venue_name
      %td= link_to 'Show', event

app/views/events/show.html.haml
%p#notice= notice

= link_to 'Back', events_path

%h1
  =@event.name
  at
  =@event.time
  with
  =@event.group_name
  at
  =@event.venue_name

=form_for current_user, url: update_notes_event_path, method: :put do |f|
  %table
    -@event.meetup_profiles.each do |attendee|
      %tr
        %td
          =attendee.name
        %td
          %a{href: attendee.photo_url}
            =image_tag attendee.photo_url, style: "max-height: 60px"
        %td
          - note = (f.object.notes.where(about: attendee).first() or Note.new(about: attendee))

          =fields_for 'notes_attributes[]', attendee, id: attendee.id do |ff|
            =ff.text_area :note_text, value: note.note_text, rows: 3
  = f.submit 'Update'

= link_to 'Back', events_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NetworkDossier</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/top/home.html.haml
%h1 Top#home
%p Find me in app/views/top/home.html.haml

- if user_signed_in?
  You're signed in!

  = link_to "Sign out", destroy_user_session_path, :method => :delete

  %h4
    Go
    =link_to "here", events_path
    to add notes
- else
  =link_to "Sign in", user_omniauth_authorize_path(:meetup)